/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Prof.v7x (https://sketchfab.com/profesor_v7x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-boss-a8d48a46c4264148974a7b7c37087e94
Title: Dragon Boss
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={46.949}>
          <group name="Dragon_Boss_05fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Dragon_Boss_05">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
                    <group name="Dragon_Boss_05_1" rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Dragon_Boss_05} skeleton={nodes.Object_8.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./scene.gltf');
